### ISSUE TITLE
Add Zed Editor

### ISSUE THREAD

**Issue by aladine** [sts10/rust-command-line-utilities#25]
Here is the link: https://github.com/zed-industries/zed
As the README page mentioned, its goal is a high-performance, multiplayer code editor from the creators of [Atom](https://github.com/atom/atom) and [Tree-sitter](https://github.com/tree-sitter/tree-sitter).

It is actively updated every week.

**Comment by sts10** [comment]
Oh, thanks! Feel like it wasn't open source before. Added.

**Comment by Hrxn** [comment]
How's that CLI?

**Comment by sts10** [comment]
>How's that CLI?

Ha, that is a good point. However, the page does have a "Text Editors" section, which is where I instinctually put it. I think it's fine to be a bit loose with the "CLI" definition... maybe it's more like "CLIs and coding tools"?

**Comment by Hrxn** [comment]
Hey, fine with me.. it's your repo 😄
