### ISSUE TITLE
Fodlereyez is one I made

### ISSUE THREAD

**Issue by jayber** [sts10/rust-command-line-utilities#6]
https://github.com/jayber/fodlereyez
A colourful folder size tui

If it floats your boat ;-)

**Comment by sts10** [comment]
Hi @jayber . Thanks for this submission. 

Unfortunately, as per [my very new and relatively arbitrary submission criteria](https://github.com/sts10/rust-command-line-utilities#criteria-for-submitting-a-tool-to-this-list), I'm going to try to wait for projects to get 100 or more stars on GitHub before adding them to the list. I hope you understand. Thanks for the submission though!
